APPCAFE-03: When selecting a row it shows CollectionViewController with mocked data
1699kratos/Prices pull request #3
Opened 2021-10-14 23:04 UTC by 1699kratos

## ISSUE: APPCAFE-03: 
https://trello.com/c/PACum6Dn

## FIX: 
when user tap a row it appears a collection view controller with the products of that cafe, again mocked data and the design is the one you showed me last time

## EVIDENCES: 
![image](https://user-images.githubusercontent.com/49655011/137407056-93a48ed0-f5c4-48cb-84a7-67ee116916c4.png)

2021-10-16 01:22 UTC, circesofia requested changes
The PR format is all wrong
The name of the PR should be the name of the ticket in trello
The issue part should have the link to the trello ticket

2021-10-16 01:22 UTC, circesofia commented on Prices/Prices/MenuViewController.swift
> +
Please delete empty lines

2021-10-16 01:22 UTC, circesofia commented on Prices/Prices/MenuViewController.swift
> +
delete empty lines here too

2021-10-16 01:22 UTC, circesofia commented on Prices/Prices/MenuViewController.swift
> +        let item = collectionView.dequeueReusableCell(withReuseIdentifier: "itemCell", for: indexPath) as! CollectionViewCell
remember to never force unwrap

2021-10-16 01:22 UTC, circesofia commented on Prices/Prices/CollectionViewCell.swift
> +
delete empty lines

2021-10-16 01:22 UTC, circesofia commented on Prices/Prices/CafeteriasViewController.swift
> +
why is this necesary?

2021-10-16 01:26 UTC, hachiosaki requested changes
The PR format is all wrong
The name of the PR should be the name of the ticket in trello
The issue part should have the link to the trello ticket
Please add images of the products, not only Tostitos verdes
VERY IMPORTANT: you cannot merge branches there's an error in APPCAFE-02 that now is here too: I'm still seeing this DS_Store file
<img width="932" alt="Captura de Pantalla 2021-10-15 a la(s) 20 39 03" src="https://user-images.githubusercontent.com/89816895/137568696-12240bea-a7c7-43aa-b3a2-1bbd66ea88e0.png">

2021-10-16 01:26 UTC, hachiosaki commented on Prices/Prices/CafeteriasViewController.swift
> +
was this necessary?

2021-10-16 01:26 UTC, hachiosaki commented on Prices/Prices/CollectionViewCell.swift
> +
delete empty lines

2021-10-16 01:26 UTC, hachiosaki commented on Prices/Prices/MenuViewController.swift
> +
delete empty lines

2021-10-16 01:26 UTC, hachiosaki commented on Prices/Prices/MenuViewController.swift
> +        let item = collectionView.dequeueReusableCell(withReuseIdentifier: "itemCell", for: indexPath) as! CollectionViewCell
never force unwrap

2021-10-16 01:26 UTC, hachiosaki commented on Prices/Prices/MenuViewController.swift
> +
delete empty lines

2021-10-19 02:36 UTC, 1699kratos commented on Prices/Prices/CafeteriasViewController.swift
> +
sorry

2021-10-19 02:44 UTC, merged